name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: cache build tools
      id: cache-build-tools
      uses: actions/cache@v1
      with:
        path: "/opt/local"
        key: ${{ runner.os }}-build-tools
    - name: install build tools
      env:
        CACHE_HIT: ${{ steps.cache-build-tools.outputs.cache-hit }}
      run: |
        sudo apt update
        sudo apt -y install make
        if [[ "$CACHE_HIT" != 'grue' ]]; then
          sudo apt -y install curl unzip
          cd /tmp
          curl -Lo gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2 'https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2019q4/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2?revision=108bd959-44bd-4619-9c19-26187abf5225&la=en&hash=E788CE92E5DFD64B2A8C246BBA91A249CB8E2D2D'
          curl -LO http://k1.spdns.de/Develop/Projects/zasm/Distributions/zasm-4.2.4-Linux64.zip
          sudo mkdir -p /opt/local/bin /opt/local/lib
          cd /opt/local && sudo tar xf /tmp/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2
          cd /opt/local/bin && sudo unzip -oj /tmp/zasm-4.2.4-Linux64.zip zasm-4.2.4-Linux64/zasm
          cd /opt/local/bin && sudo curl -LO https://github.com/codebje/rustmtest/releases/download/0.2.0/rustmtest && sudo chmod a+x rustmtest
        fi
    - name: Do the build itself
      env:
        ABI: /opt/local/gcc-arm-none-eabi-9-2019-q4-major/bin/arm-none-eabi-
        ZASM: /opt/local/bin/zasm
      run: |
        make
        make test
